// This is the minimal root layout for your entire application.
import './globals.css'; // You can keep global styles here.

export const metadata = {
  title: 'My App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
